name: lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4

      - name: Lint JSON and YAML files
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@ce9d0c1ff859732d3839a5e1cdc22ff203aa464a  # v2.4.0
        with:
          comment: "true" # enable comment mode
