name: validate-projects

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7  # v1

      - name: Install dependencies
        run: bun install

      - name: Validate projects against Zod schemas
        run: bun scripts/projectValidation/projectValidation.ts
